### ISSUE TITLE
QUICKBLOX ERROR:Error: Failed to execute 'send' on 'WebSocket': Still in CONNECTING state.

### ISSUE THREAD

**Issue by priyankpatel40** [QuickBlox/quickblox-javascript-sdk#218]
Hello,
I am getting Error: Failed to execute 'send' on 'WebSocket': Still in CONNECTING state. because of that i am not able to send or receive any messages or calls.
Please, help me how to resolve this Connecting state error through code.

**Comment by dimaspirit** [comment]
@priyankpatel40 , please use the form and give us initial information.

FORM:
**Environment details**
*(Operating system, browser information, SDK version)*


**Did this work before?**


**Expected behavior**


**Actual behavior**


**Logs**
*(please, switch on a [debugging mode](http://quickblox.com/developers/Javascript#Configuration) and share us outputs uses github [gist](https://gist.github.com/))*

**Comment by priyankpatel40** [comment]
![untitled2](https://cloud.githubusercontent.com/assets/26541975/24693268/5e3b1202-19fa-11e7-9cc9-93a0b91218b8.png)
Environment details
(Operating system, browser information, SDK version)
Windows 10,Mac
Chrome,Safari,opera
SDK:2.2.2

Did this work before?
It is working mostly but sometime it shows above error

Expected behavior
Should not stay in Connecting State with websockets.

Actual behavior
Sometimes it stays in connecting state and nothing works then no incoming/outgoing calls and messages and no message history

**Comment by dimaspirit** [comment]
Sure you need to connected before make `send`. And call another request in callback which fire after connect.
Now we don't have `isConnect` methods so you need to realize this logic by yourself.
