### ISSUE TITLE
Android stuck after calling with web

### ISSUE THREAD

**Issue by lufyitbkdn** [QuickBlox/quickblox-javascript-sdk#219]
1. Environment details
- Android: QB SDK 3.3.0
- Web RTC - Web: 2.4

2. Expected behavior:
- App can receive call after calling with Web

3. Actual behavior (100%):
- App cannot receive call  calling with Web (call started and web ends the call).

4. Steps to reproduce the behavior:
 - Android call to web (or web call Android). 
 - Web accept call
 - After started call, web end the call. Android cannot receive hangup listener and will end call when receive ConnectionClosedForUser. After that, android cannot receive any call (from Android, iOS, Web).

This problem is not happen when calling Android with Android or Android with iOS. And iOS has no problem with web

**Comment by dimaspirit** [comment]
@lufyitbkdn  Are you using Qmunicate? Which version of QM are you using?

**Comment by lufyitbkdn** [comment]
@dimaspirit I don't use Qmunicate. I do as [sample from Quick Blox](https://github.com/QuickBlox/quickblox-android-sdk/tree/master/sample-videochat-webrtc)

**Comment by sloutions3e** [comment]
# Android stuck after calling with web
Even I am facing the same issue
I've tested the following-

Between two android devices. - WORKED
Between Android Device and IOS Device - WORKED
Between Android Device and Desktop - DID NOT WORK

### Environment details
Android: QB SDK 3.0
Web RTC - Web: 2.5

### Expected behaviour:
App should get the accept acknowledgement once the other person accepts the call.

### Actual behaviour (100%):
While communicating with desktop client, android is not receiving the accept acknowledgement from other end.
Android to android - successful communication
Android to IOS - successful communication
Android to desktop -  communication fails


### Steps to reproduce the behaviour:

- Do a call from android to desktop client
- Desktop client accepts the call.

Android is not receiving the accept listener from the desktop client.
This problem is not happening while calling Android with Android or Android with iOS.
Note that iOS has no problem with web

Please provide a solution ASAP.

**Comment by ghost** [comment]
Hello QuickBlox customer,

This is Nikolay from QuickBlox support.

The issue was closed as it was outdated.

Please update the SDKs to the latest versions:
[https://github.com/QuickBlox/quickblox-android-sdk-releases/releases/tag/3.9.11](https://github.com/QuickBlox/quickblox-android-sdk-releases/releases/tag/3.9.11)
[https://github.com/QuickBlox/quickblox-javascript-sdk/releases/tag/2.13.10](https://github.com/QuickBlox/quickblox-javascript-sdk/releases/tag/2.13.10)

Additionally, please check our new samples:
[https://docs.quickblox.com/docs/code-samples#video-calling-samples](https://docs.quickblox.com/docs/code-samples#video-calling-samples)

If it is still relevant after reviewing the updated information, feel free to open a new issue.

Have a nice day.

**Comment by EderNocelo** [comment]
Hello, I have the same issue. 

**JavaScript** environment  2.13.10
**Android** environment 3.9.15 

After 4-5 minutes on call _QBRTCClientSessionCallbacks_ not works correctly. In the next image you can see the Logs of callbacks. 

They are 13-15 Seconds between _onDisconnectedFromUser_ and _onConnectionFailedWithUser_ (I don't know why... I think _onReceiveHangUpFromUser_ should be called instead of _onConnectionFailedWithUser_)

<img width="1125" alt="Captura de pantalla 2022-03-03 a las 16 48 21" src="https://user-images.githubusercontent.com/5324231/156673686-468584d8-a88a-4fb9-a9bd-cbf2b8120d85.png">

Also as you can see _onReceiveHangUpFromUser_ never executes. 

Can you help me?

**Note: ** When call duration is between 1-2 minutes works like a charm

**Comment by EderNocelo** [comment]
[](https://user-images.githubusercontent.com/5324231/156673686-468584d8-a88a-4fb9-a9bd-cbf2b8120d85.png)Hello, I have the same issue.

JavaScript environment 2.13.10
Android environment 3.9.15

After 4-5 minutes on call _QBRTCClientSessionCallbacks_ not works correctly. In the next image you can see the Android Logs of callbacks.

They are 13-15 Seconds between _onDisconnectedFromUser_ and _onConnectionFailedWithUser_ (I don't know why... I think _onReceiveHangUpFromUser_ should be called instead of _onConnectionFailedWithUser_)

<img width="1125" alt="Captura de pantalla 2022-03-03 a las 16 48 21" src="https://user-images.githubusercontent.com/5324231/156675102-d14571a7-beac-4f84-ba94-69e9fc718035.png">

Also as you can see _onReceiveHangUpFromUser_ never executes.

Can you help me?

**Note:** When call duration is between 1-2 minutes works like a charm

**Comment by ghost** [comment]
@EderNocelo Hello,

This is Nikolay from QuickBlox support.

Please try reproducing the issue on our samples:
https://docs.quickblox.com/docs/code-samples#video-calling-samples

Also, please provide us with steps to reproduce the issue.
