### ISSUE TITLE
Video/Audio Chat disconnects after random time interval

### ISSUE THREAD

**Issue by hiteshagja** [QuickBlox/quickblox-javascript-sdk#250]
I have integrated quickblox refering your webrtc javascript example and I am facing call disconnection issue. Call is getting disconnect between 20-28 seconds. Why is this happening? Is there any API limitation for starter plan? Help me solve this issue.

**Comment by dimaspirit** [comment]
Hi, we don't have any limits on call. Could you check any issues in developer's cosole?

**Comment by hiteshagja** [comment]
@dimaspirit 

Getting error like this

[QBWebRTC]: Error on 'addIceCandidate': OperationError: Error processing ICE candidate

[QBWebRTC]: Ignore 'onStop', there is no information about session c3f96224-7db7-48d9-8689-2e50c82542a6 by some reason.

I am getting connectionState=6 and then connectionState=5 in onSessionConnectionStateChangedListener after 20+ seconds. And this is persistent.

**Comment by hiteshagja** [comment]
@dimaspirit 

[QBWebRTC]: 'setRemoteSessionDescription' error: OperationError: Failed to set remote offer sdp: Called in wrong state: STATE_SENTOFFER 

this error always comes when someone accept my call.

**Comment by dimaspirit** [comment]
@hiteshagja what a browser / OS and steps to reproduce?

**Comment by dimaspirit** [comment]
@hiteshagja any updates? Are you fix this case?

**Comment by ghost** [comment]
Hello QuickBlox customer,

This is Nikolay from QuickBlox support.

The issue was closed as it was outdated.

Please check the relevant section of our documentation here:
[https://docs.quickblox.com/docs/js-video-calling](https://docs.quickblox.com/docs/js-video-calling)

Also, please update the SDK to the latest version:
[https://github.com/QuickBlox/quickblox-javascript-sdk/releases/tag/2.13.10](https://github.com/QuickBlox/quickblox-javascript-sdk/releases/tag/2.13.10)

Additionally, please check our new sample:
[https://github.com/QuickBlox/quickblox-javascript-sdk/tree/gh-pages/samples/webrtc](https://github.com/QuickBlox/quickblox-javascript-sdk/tree/gh-pages/samples/webrtc)

If it is still relevant after reviewing the updated information, feel free to open a new issue.

Have a nice day.
