### ISSUE TITLE
Update last message when delete message performed

### ISSUE THREAD

**Issue by ayushishah-easternts** [QuickBlox/quickblox-javascript-sdk#293]
SDK version : 2.5

Hi ,

How to handle the display of last message in dialog listing if the user deletes the last message of that particular dialog for oneself i.e no force delete? In this case any workaround to update the dialog listing with updated last message?

Here we are using QB.chat.message.delete is the method we are using for deleting message.

**Comment by vadimkhmyrovqb** [comment]
@AyushiBShah Hi, this issue is not related to Javascript SDK, but rather to API functionality. Regarding API, please refer to this documentation https://quickblox.com/developers/Chat . If you have more questions, please submit a [ticket](https://assist.quickblox.com/index.php?/Core/Default/Index) with Quickblox.
