### ISSUE TITLE
Recorded Video not having audio stream from web (js), Only voice from Android Client being recorded

### ISSUE THREAD

**Issue by asdec** [QuickBlox/quickblox-javascript-sdk#327]
So our product that we are trying to achieve is as follows:

1. Mobile App (The Client) : We have an Android App with QB Sdk.  The App logs into a chatroom and receives a call. The App can share screen as well.
2. Web Panel (Admin) : Here, the Admin user is logged into the same chat-room. The Admin is shown the list of users (App users) who have logged into the same chatroom. The Admin makes One-to-One video calls to these users. After call disconnection , the video of the session is saved at the web-panel (not Android App) and the video is stored. 

The recorded video consists of :
1. Video session of the Android User (Camera/Screen)
2. Audio of the Android User

But, not the Audio of the Admin user who interacted with the Android user throughout the session. The Video seams missing the Audio stream from web/laptop microphone. We need both the Audio (Both Android User and Web Admin user)

Yes, We are using QBMediaRecorder (v.2.0.0). Our JS SDK Version : v.2.9.0.1073

**Comment by dimaspirit** [comment]
@asdec hi.
QBMediaRecorder based on [MediaRecorder](https://developer.mozilla.org/en-US/docs/Web/API/MediaRecorder), so first need to understand browser API recorder.

Also, note that QBMediaRecorder takes only 1 stream and record them. So, if you make a call you will get 2 streams (local and remote). And you need to create 2 instances of QBMediaRecorder and record both.

Thanks for your explanation but we need more technical explanation. For example, a snippet of code "how you set up a call and a record".

**Comment by asdec** [comment]
please help me with how to record multiple streams as i can see only 1 stream in QBMediaRecorder. We are using your core application downloaded from here  https://github.com/QuickBlox/quickblox-javascript-sdk

**Comment by vadimkhmyrovqb** [comment]
@asdec Please share a code snippet so we can investigate what part of QB functionality is not working correctly.

**Comment by ghost** [comment]
Hello QuickBlox customer,

This is Nikolay from QuickBlox support.

The issue was closed as it was outdated.

The feature of recording audio/video calls is available only for conference calls.
Conference audio/video calls functionality is provided as an addon for all paid plans.
You may read more here:
[https://quickblox.com/pricing/](https://quickblox.com/pricing/)
In order to use the video conference calling feature, you need to purchase a dedicated Janus server.

Server side recording functionality can be enabled/disabled for the entire server from our side. Every call will be recorded if the feature is enabled.

Audio and video files are recorded for each user separately and stored on the server.

If you are interested in audio/video conference functionality and call recording, feel free to [contact our Sales team ](https://quickblox.com/enterprise/#get-enterprise)to get more information.

If there are any further questions, please submit a new issue.
