### ISSUE TITLE
Can't accept the session in onCallListener

### ISSUE THREAD

**Issue by niccolofanton** [QuickBlox/quickblox-javascript-sdk#335]
I'm using Quickblox JS in my Ionic 3 project.   

**Environment details**
*(Operating system, browser information, SDK version)*
I'm using iOS 10.3.3, ionic 3.20, cordova 8.0, quickblox.min.js 2.11, cordova-plugin-iosrtc

**Did this work before?**
No.

**Expected behavior**
Start the video-call.

**Actual behavior**
Error "Can't accept the call, there is no information about peer connection by some reason." when session.accept({});

**Logs**
https://gist.github.com/niccolofanton/9be410e30c8771139ffe14dbf9e05d93

**Steps to reproduce the behavior**
My code
https://gist.github.com/niccolofanton/b54927ebba17eedc84cc6530b5bcf330

**Any others comments?**
Working in android

**Comment by vadimkhmyrovqb** [comment]
@niccolofanton Can you reproduce it with JS SDK 2.12.2 ?

**Comment by TarunNarula** [comment]
have you found any solution of this ?

**Comment by ghost** [comment]
Hello QuickBlox customer,

This is Nikolay from QuickBlox support.

The issue was closed as it was outdated.

Please check the relevant section of our documentation here:
[https://docs.quickblox.com/docs/js-video-calling](https://docs.quickblox.com/docs/js-video-calling)

Also, please update the SDK to the latest version:
[https://github.com/QuickBlox/quickblox-javascript-sdk/releases/tag/2.13.10](https://github.com/QuickBlox/quickblox-javascript-sdk/releases/tag/2.13.10)

Additionally, please check our new sample:
[https://github.com/QuickBlox/quickblox-javascript-sdk/tree/gh-pages/samples/webrtc](https://github.com/QuickBlox/quickblox-javascript-sdk/tree/gh-pages/samples/webrtc)

If it is still relevant after reviewing the updated information, feel free to open a new issue.

Have a nice day.
