### ISSUE TITLE
Unable to access android camera in <iframe> tag in ionic3 project for quickblox 

### ISSUE THREAD

**Issue by bsuyog16** [QuickBlox/quickblox-javascript-sdk#345]
Environment Details :

 - OS : ubuntu 16.04 lts
 - Angular : 4
 - cordova (Cordova CLI) : 7.0.1 
 - Ionic Framework : 3.9.2
 - Android SDK Tools : 26.0.2

I am using `<iframe>` tag in ionic3 html page. `<iframe>` is referring to quickblox java-script SDK which is kept inside `src/assets` directory.

    `<iframe` class="quickblox-view" src="assets/webrtc/index.html"></iframe>`

But when I am trying for video call,I am not able to access android device camera. Also I can see error message on page as  `Error: devices (camera or microphone) are not found` which is error defined in quickblox project itself.

Please help.

**Steps to reproduce the behavior**
1. Download quickblox javasctipt SDK 
2. Keep SDK inside src/assets of ionic project.
3. Write a code in html as follows :
 `<iframe` class="quickblox-view" src="assets/webrtc/index.html"></iframe>`
4. Build  APK and try to video call .

**Comment by ghost** [comment]
Hello QuickBlox customer,

This is Nikolay from QuickBlox support.

The issue was closed as it was outdated.

Please check the relevant section of our documentation here:
[https://docs.quickblox.com/docs/js-video-calling](https://docs.quickblox.com/docs/js-video-calling)

Also, please update the SDK to the latest version:
[https://github.com/QuickBlox/quickblox-javascript-sdk/releases/tag/2.13.10](https://github.com/QuickBlox/quickblox-javascript-sdk/releases/tag/2.13.10)

Additionally, please check our new sample:
[https://github.com/QuickBlox/quickblox-javascript-sdk/tree/gh-pages/samples/webrtc](https://github.com/QuickBlox/quickblox-javascript-sdk/tree/gh-pages/samples/webrtc)

If it is still relevant after reviewing the updated information, feel free to open a new issue.

Have a nice day.
