### ISSUE TITLE
Purge message history from nodejs

### ISSUE THREAD

**Issue by SnuK87** [QuickBlox/quickblox-javascript-sdk#350]
Is it possible to delete all messages from the history in the backend?

When I delete a message with `QB.chat.message.delete` and `{force: 1}` I get the expected result but it's only possible for my own messages. For messages written by other users I get a `403` response as explained in the docs for the JS SDK and REST API.

Currently the only way I see is deleting messages manually via the admin dashboard but I'm looking for a way to do the same from my node js application.

**Comment by vadimkhmyrovqb** [comment]
Hi, this issue is not related to Javascript SDK, but rather to API functionality. Regarding API, please refer to this documentation https://quickblox.com/developers/Chat . If you have more questions, please submit a [ticket] (https://assist.quickblox.com/index.php?/Core/Default/Index) with Quickblox.
