### ISSUE TITLE
getUserMedia - Audio

### ISSUE THREAD

**Issue by williamtran1988** [QuickBlox/quickblox-javascript-sdk#367]
Hi All,

I am building a WebRTC application by using QT as WebEngine. I used Quickblox Javascript SDK to build WebRTC feature.

In my application i used SetWindowsHookEx to trigger all keyboard event. Everything was working well until i make a WebRTC call. The keyboard trigger event could not be catched anymore. Exactly the problem happen when i use getUserMedia feature.

Do you have any ideas?

BR,
William.

**Comment by ghost** [comment]
Hello QuickBlox customer,

This is Nikolay from QuickBlox support.

The issue was closed as it was outdated.

Please check the relevant section of our documentation here:
[https://docs.quickblox.com/docs/js-video-calling](https://docs.quickblox.com/docs/js-video-calling)

Also, please update the SDK to the latest version:
[https://github.com/QuickBlox/quickblox-javascript-sdk/releases/tag/2.13.10](https://github.com/QuickBlox/quickblox-javascript-sdk/releases/tag/2.13.10)

Additionally, please check our new sample:
[https://github.com/QuickBlox/quickblox-javascript-sdk/tree/gh-pages/samples/webrtc](https://github.com/QuickBlox/quickblox-javascript-sdk/tree/gh-pages/samples/webrtc)

If it is still relevant after reviewing the updated information, feel free to open a new issue.

Have a nice day.
