### ISSUE TITLE
Safari Video Stream not seen on other browsers

### ISSUE THREAD

**Issue by aliabbas12** [QuickBlox/quickblox-javascript-sdk#371]
**Environment details**
Latest javascript web SDK 2.12.2. 
Latest Safari browser: 12
Latest Chrome Broswer

**Did this work before?**
We have tested chrome to chrome call and firefox calls and it works fine. Safari is not streaming the video and we only see a black screen on the other device. Safari can see the video of the other device but there is not audio

**Expected behavior**
Expected behavior is when we call from safari to other browsers and other browsers to safari the video should work on both ends.

**Actual behavior**
When we call from Safari to other browser (chrome in our case),
1. Chrome does not see the streamed video from safari browser only black screen is there
2. Safari can see the video stream from chrome but there is no audio

When we use chrome to chrome call, both streams and audio are working without any issues

**Steps to reproduce the behavior**
1. Login one user on Chrome and the other user on Safari
2. Initiate the call from safari
3. Black screen on chrome for video stream of safari
4. No audio on safari for the video stream coming from chrome.

**Any others comments?**
No errors shown for the stream issue. Not sure what is causing the issue as it should work.

**Comment by aliabbas12** [comment]
We have also tried using the javascript sdk on mobile by integrating it in ionic 3 as call receiving client and here is what we see there:

when the call is initiated from Chrome, we can see it working on both android and ios device
when the call is initiated from Safari web, we cannot see the stream on android or ios device.

The issue is a major release blocker for us and is really stopping the project launch.
@QB-vladyslav-vyshniak can you please help us get this resolved soon. Once we can prove the concept works, then the client will be surely moving to a paid platform to have all the use cases covered.

**Comment by Umashankarsaw** [comment]
I have the same issue as mentioned @aliabbas12  with angular, but still not get any solution, I am requesting quickblox to develop a video call sample in angular(with well tested with iphone), so that we can buy quickblox paid platform.

Thanks

**Comment by ghost** [comment]
Hello QuickBlox customer,

This is Nikolay from QuickBlox support.

The issue was closed as it was outdated.

Please check the relevant section of our documentation here:
[https://docs.quickblox.com/docs/js-video-calling](https://docs.quickblox.com/docs/js-video-calling)

Also, please update the SDK to the latest version:
[https://github.com/QuickBlox/quickblox-javascript-sdk/releases/tag/2.13.10](https://github.com/QuickBlox/quickblox-javascript-sdk/releases/tag/2.13.10)

Additionally, please check our new sample:
[https://github.com/QuickBlox/quickblox-javascript-sdk/tree/gh-pages/samples/webrtc](https://github.com/QuickBlox/quickblox-javascript-sdk/tree/gh-pages/samples/webrtc)

If it is still relevant after reviewing the updated information, feel free to open a new issue.

Have a nice day.
