### ISSUE TITLE
I am getting issue : ReferenceError: QB is not defined

### ISSUE THREAD

**Issue by konstantsolutions** [QuickBlox/quickblox-javascript-sdk#372]
I am using this repository. When i run "ionic serve" after "npm install", it is showing error that 
ReferenceError: QB is not defined

Please provide solutions.

Thanks.

**Comment by ghost** [comment]
Hello QuickBlox customer,

This is Nikolay from QuickBlox support.

The issue was closed as it was outdated.

Please update the SDK to the latest version:
[https://github.com/QuickBlox/quickblox-javascript-sdk/releases/tag/2.13.10](https://github.com/QuickBlox/quickblox-javascript-sdk/releases/tag/2.13.10)

Additionally, please check our new sample:
[https://github.com/QuickBlox/quickblox-javascript-sdk/tree/gh-pages/samples/chat](https://github.com/QuickBlox/quickblox-javascript-sdk/tree/gh-pages/samples/chat)

If it is still relevant after reviewing the updated information, feel free to open a new issue.

Have a nice day.
