### ISSUE TITLE
TypeError: Cannot read property 'ondevicechange' of undefined

### ISSUE THREAD

**Issue by vivekdoshi2** [QuickBlox/quickblox-javascript-sdk#378]
**How we init QuickBlox :**
Generating token from server side ( node js ) , then init QuickBlox with token and app id

**Step to produce issue :**
Serving angular project on host:port eg. http://192.168.15.100:4200 ( local server )
Now if me and my colleague opens the url and login with same user and init Quickblox then it throws error

**Error :**

```
TypeError: Cannot read property 'ondevicechange' of undefined
    at new u (quickblox.min.js:1)
    at s.init (quickblox.min.js:1)
    at quickblox.service.ts:132
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke (zone.js:388)
    at Object.onInvoke (core.js:3824)
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke (zone.js:387)
    at Zone.push../node_modules/zone.js/dist/zone.js.Zone.run (zone.js:138)
    at zone.js:872
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:421)
    at Object.onInvokeTask (core.js:3815)
```

> at quickblox.service.ts:132 // This is the line where I am inited Quickblox

`QB.init(token, appId , null , config);`

#351 , Have also posted on this ticket but as it was closed, that might not get updated.

**Comment by zeljkocurcic** [comment]
Any news on this one? We still have the same issue and it's been almost a year

**Comment by saymo23** [comment]
Try running in secure protocol (https), works for my.

**Comment by Suraj6198** [comment]
Everything working fine on the localhost. But on the server it is giving the same error for me. If anyone solved, please help.

**Comment by dmartinezenfocado** [comment]
@Suraj6198  i have the same error

**Comment by dmartinezenfocado** [comment]
@saymo23 Thanks, after installing the SSL certificate and access https works for my too

**Comment by jaws97** [comment]
If you see "Not Secure" on your browser URL, BigBlueButton will not load. Install SSL certificate and access from HTTPS

**Comment by ghost** [comment]
Hello QuickBlox customer,

This is Nikolay from QuickBlox support.

The issue was closed as it was outdated.

Please update the SDK to the latest version:
[https://github.com/QuickBlox/quickblox-javascript-sdk/releases/tag/2.13.10](https://github.com/QuickBlox/quickblox-javascript-sdk/releases/tag/2.13.10)

Additionally, please check our new samples:
[https://github.com/QuickBlox/quickblox-javascript-sdk/tree/gh-pages/samples/chat](https://github.com/QuickBlox/quickblox-javascript-sdk/tree/gh-pages/samples/chat)

If it is still relevant after reviewing the updated information, feel free to open a new issue.
