### ISSUE TITLE
How to make video calls in NativeScript

### ISSUE THREAD

**Issue by Izrab** [QuickBlox/quickblox-javascript-sdk#380]
I could not find any resources on how to make video calls in NativeScript.
QuickBlox provides very scarce and limited docs (if any) for NativeScript, no guide for installation and configuration at all!
I just want to make video calls in nativescript how?!

**Comment by ghost** [comment]
ello QuickBlox customer,

This is Nikolay from QuickBlox support.

The issue was closed as it was outdated.

Please check the relevant section of our documentation here:
[https://docs.quickblox.com/docs/js-video-calling](https://docs.quickblox.com/docs/js-video-calling)

Also, please update the SDK to the latest version:
[https://github.com/QuickBlox/quickblox-javascript-sdk/releases/tag/2.13.10](https://github.com/QuickBlox/quickblox-javascript-sdk/releases/tag/2.13.10)

Additionally, please check our new sample:
[https://github.com/QuickBlox/quickblox-javascript-sdk/tree/gh-pages/samples/webrtc](https://github.com/QuickBlox/quickblox-javascript-sdk/tree/gh-pages/samples/webrtc)

If it is still relevant after reviewing the updated information, feel free to open a new issue.

Have a nice day.
