### ISSUE TITLE
Not working on iOS (cordova)

### ISSUE THREAD

**Issue by phyr0s** [QuickBlox/quickblox-javascript-sdk#382]
**Environment details**
*(Operating system, browser information, SDK version)*
iOS lastest version
SDK Javascript Lastest https://cdnjs.cloudflare.com/ajax/libs/quickblox/2.12.4/quickblox.min.js

works on desktop but launching on  phone i always get  "Error: devices camera or microphone are not found.

All phone permission (camera and microphone) are requested

You can see easily that is not working using quickblox cordova demo 
https://quickblox.com/developers/Sample-webrtc-cordova#Android_WebRTC_support

**Comment by ghost** [comment]
Hello QuickBlox customer,

This is Nikolay from QuickBlox support.

The issue was closed as it was outdated.

Please check the relevant section of our Javascript documentation here:
[https://docs.quickblox.com/docs/js-video-calling](https://docs.quickblox.com/docs/js-video-calling)

Also, please update the SDK to the latest version:
[https://github.com/QuickBlox/quickblox-javascript-sdk/releases/tag/2.13.10](https://github.com/QuickBlox/quickblox-javascript-sdk/releases/tag/2.13.10)

Additionally, please check our new Javascript sample:
[https://github.com/QuickBlox/quickblox-javascript-sdk/tree/gh-pages/samples/webrtc](https://github.com/QuickBlox/quickblox-javascript-sdk/tree/gh-pages/samples/webrtc)

If it is still relevant after reviewing the updated information, feel free to open a new issue.

Have a nice day.
