### ISSUE TITLE
Help me to record audio call into text.

### ISSUE THREAD

**Issue by tiny0101** [QuickBlox/quickblox-javascript-sdk#383]
Is there any way to record audio call into text.
Or how can I use google cloud speech to text api with quickblox.

**Comment by ghost** [comment]
Hello QuickBlox customer,

This is Nikolay from QuickBlox support.

The issue was closed as it was outdated.

Unfortunately, we have not implemented a speech-to-text module. You may implement such a feature at the client-side part.

If it is still relevant after reviewing the updated information, feel free to open a new issue.

Have a nice day.
